# -*- mode: ruby -*-
# vi: set ft=ruby :

@allhosts = {
  vm1: {
    hostname:     "CentOS6vm1",
    ip:           "192.168.56.121",
    netmask:      "255.255.255.0",
    network_type: "private_network",   #or public_network, or forwarded_port
    gui:          false,
    memory:       "768",
    command: [
      "yum install httpd -y",
      "service httpd start",
    ],
  },

  vm2: {
    hostname:     "CentOS6vm2",
    ip:           "192.168.56.122",
    netmask:      "255.255.255.0",
    network_type: "private_network",   #or public_network, or forwarded_port
    gui:          false,
    memory:       "1024",
    command: [
      "yum install samba -y",
      "service smb start",
      "service nmb start",
    ],
  },
}

load "./Vagrantfile.common" if File.exist?("./Vagrantfile.common")
