$hostname = "CentOS6vm"
$ip = "192.168.100.122"
$netmask = "255.255.255.0"
$gw = "192.168.100.1"

Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "768"
  end

  config.vm.network "public_network",
      ip: $ip,
    netmask: $netmask
  config.vm.provision "shell",
    run: "always",
    inline: "route add default gw " + $gw
  config.vm.provision "shell",
    run: "always",
    inline: "echo GATEWAY=" + $gw + "| sudo tee -a /etc/sysconfig/network-scripts/ifcfg-eth1"
  
##begin your provisioning
#
#  config.vm.provision "shell",
#    run: "always",
#    inline: "yum install httpd -y"
#  config.vm.provision "shell",
#    run: "always",
#    inline: "chkconfig httpd on"
#
###end your provisioning
  
end

load "../Common/Vagrantfile.common" if File.exist?("../Common/Vagrantfile.common")