$script_kb_CUI = <<SCRIPT
cat << "EOS" | sudo tee "/etc/default/console-setup"
KEYTABLE="jp106"
MODEL="jp106"
LAYOUT="jp"
KEYBOARDTYPE="pc"
EOS
SCRIPT

$script_kb_GUI = <<SCRIPT
cat << "EOS" | sudo tee "/etc/default/keyboard"
XKBMODEL="pc105"
XKBLAYOUT="jp,jp"
XKBVARIANT=""
XKBOPTIONS=""

BACKSPACE="guess"
EOS
SCRIPT

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
    vb.memory = "1024"
  end

  config.vm.box = "cxtlabs/vagrant-ubuntu-16.04-mate"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.host_name = "UbuntuMATE16vm"

  config.vm.network "public_network",
    ip: "192.168.100.203",
    netmask: "255.255.255.0"

  config.vm.provision "shell",
    run: "always",
    inline: "route add default gw 192.168.100.1"
  config.vm.provision "shell",
    run: "always",
    inline: "eval `route -n | awk '{ if ($8 ==\"eth0\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
  config.vm.provision "shell",
    run: "always",
    inline: "sed -i -e 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config"
  config.vm.provision "shell",
    run: "always",
    inline: $script_kb_CUI
  config.vm.provision "shell",
    run: "always",
    inline: $script_kb_GUI
  config.vm.provision "shell",
    run: "always",
    inline: "shutdown -r now"

end
