# make sure to install vagrant-alpine plugin before you run 'vagrant up'.
# vagrant plugin install vagrant-alpine

Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "128"
    vb.cpus = 1
  end

  config.vm.box = "maier/alpine-3.1.3-x86_64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  1.upto(30) do |i|
     config.vm.define "vm#{i}" do |v|
      v.vm.host_name = "alpinevm#{i}"
      v.vm.network "public_network",
        ip: "192.168.100.#{i + 50}",
        netmask: "255.255.255.0"
    end
  end
end
