$hostname1 = "CentOS7vm1"
$ip1 = "192.168.100.121"
$netmask1 = "255.255.255.0"
$gw1 = "192.168.100.1"

#$hostname2 = "CentOS7vm2" #if you want to build multiple vms
#$ip2 = "192.168.100.122"
#$netmask2 = "255.255.255.0"
#$gw2 = "192.168.100.1"


Vagrant.configure("2") do |config|
  
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "768"
  end

  config.vm.define "vm1" do |vm1|
    vm1.vm.host_name = $hostname1
    vm1.vm.network "public_network",
      ip: $ip1,
      netmask: $netmask1
    vm1.vm.provision "shell",
      run: "always",
      inline: "nmcli con mod 'System eth1' ipv4.gateway " + $gw1
    
#    #begin your provisioning
#    
#    vm1.vm.provision "shell",
#      run: "always",
#      inline: "yum install httpd -y"
#    vm1.vm.provision "shell",
#      run: "always",
#      inline: "systemctl start httpd"
#    
#    #end your provisioning
    
    vm1.vm.provision "shell",
      run: "always",
      inline: $reboot
    
  end
  
#  config.vm.define "vm2" do |vm2|  #if you want to build multiple vms
#    vm2.vm.host_name = $hostname2
#    vm2.vm.network "public_network",
#      ip: $ip2,
#      netmask: $netmask2
#    vm2.vm.provision "shell",
#      run: "always",
#      inline: "nmcli con mod 'System eth1' ipv4.gateway " + $gw2
#    
##    #begin your provisioning
##    
##    vm2.vm.provision "shell",
##      run: "always",
##      inline: "yum install httpd -y"
##    vm2.vm.provision "shell",
##      run: "always",
##      inline: "systemctl start httpd"
##    
##    #end your provisioning
#    
#    vm2.vm.provision "shell",
#      run: "always",
#      inline: $reboot
#    
#  end

end

load "../Common/Vagrantfile.common" if File.exist?("../Common/Vagrantfile.common")