Vagrant.configure("2") do |config|

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.memory = "128"
  end
  
  config.vm.box = "maier/alpine-3.1.3-x86_64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

config.vm.define "vm1" do |vm1|
  vm1.vm.host_name = "alpinevm1"
  vm1.vm.network "public_network",
    ip: "192.168.100.201",
    netmask: "255.255.255.0"
end

config.vm.define "vm2" do |vm2|
  vm2.vm.host_name = "alpinevm2"
  vm2.vm.network "public_network",
    ip: "192.168.100.202",
    netmask: "255.255.255.0"
end

config.vm.define "vm3" do |vm3|
  vm3.vm.host_name = "alpinevm3"
  vm3.vm.network "public_network",
    ip: "192.168.100.203",
    netmask: "255.255.255.0"
end

config.vm.define "vm4" do |vm4|
  vm4.vm.host_name = "alpinevm4"
  vm4.vm.network "public_network",
    ip: "192.168.100.204",
    netmask: "255.255.255.0"
end

config.vm.define "vm5" do |vm5|
  vm5.vm.host_name = "alpinevm5"
  vm5.vm.network "public_network",
    ip: "192.168.100.205",
    netmask: "255.255.255.0"
end

config.vm.define "vm6" do |vm6|
  vm6.vm.host_name = "alpinevm6"
  vm6.vm.network "public_network",
    ip: "192.168.100.206",
    netmask: "255.255.255.0"
end

config.vm.define "vm7" do |vm7|
  vm7.vm.host_name = "alpinevm7"
  vm7.vm.network "public_network",
    ip: "192.168.100.207",
    netmask: "255.255.255.0"
end

config.vm.define "vm8" do |vm8|
  vm8.vm.host_name = "alpinevm8"
  vm8.vm.network "public_network",
    ip: "192.168.100.208",
    netmask: "255.255.255.0"
end

config.vm.define "vm9" do |vm9|
  vm9.vm.host_name = "alpinevm9"
  vm9.vm.network "public_network",
    ip: "192.168.100.209",
    netmask: "255.255.255.0"
end

config.vm.define "vm10" do |vm10|
  vm10.vm.host_name = "alpinevm10"
  vm10.vm.network "public_network",
    ip: "192.168.100.210",
    netmask: "255.255.255.0"
end

config.vm.define "vm11" do |vm11|
  vm11.vm.host_name = "alpinevm11"
  vm11.vm.network "public_network",
    ip: "192.168.100.211",
    netmask: "255.255.255.0"
end

config.vm.define "vm12" do |vm12|
  vm12.vm.host_name = "alpinevm12"
  vm12.vm.network "public_network",
    ip: "192.168.100.212",
    netmask: "255.255.255.0"
end

config.vm.define "vm13" do |vm13|
  vm13.vm.host_name = "alpinevm13"
  vm13.vm.network "public_network",
    ip: "192.168.100.213",
    netmask: "255.255.255.0"
end

config.vm.define "vm14" do |vm14|
  vm14.vm.host_name = "alpinevm14"
  vm14.vm.network "public_network",
    ip: "192.168.100.214",
    netmask: "255.255.255.0"
end

config.vm.define "vm15" do |vm15|
  vm15.vm.host_name = "alpinevm15"
  vm15.vm.network "public_network",
    ip: "192.168.100.215",
    netmask: "255.255.255.0"
end

config.vm.define "vm16" do |vm16|
  vm16.vm.host_name = "alpinevm16"
  vm16.vm.network "public_network",
    ip: "192.168.100.216",
    netmask: "255.255.255.0"
end

config.vm.define "vm17" do |vm17|
  vm17.vm.host_name = "alpinevm17"
  vm17.vm.network "public_network",
    ip: "192.168.100.217",
    netmask: "255.255.255.0"
end

config.vm.define "vm18" do |vm18|
  vm18.vm.host_name = "alpinevm18"
  vm18.vm.network "public_network",
    ip: "192.168.100.218",
    netmask: "255.255.255.0"
end

config.vm.define "vm19" do |vm19|
  vm19.vm.host_name = "alpinevm19"
  vm19.vm.network "public_network",
    ip: "192.168.100.219",
    netmask: "255.255.255.0"
end

config.vm.define "vm20" do |vm20|
  vm20.vm.host_name = "alpinevm20"
  vm20.vm.network "public_network",
    ip: "192.168.100.220",
    netmask: "255.255.255.0"
end

config.vm.define "vm21" do |vm21|
  vm21.vm.host_name = "alpinevm21"
  vm21.vm.network "public_network",
    ip: "192.168.100.221",
    netmask: "255.255.255.0"
end

config.vm.define "vm22" do |vm22|
  vm22.vm.host_name = "alpinevm22"
  vm22.vm.network "public_network",
    ip: "192.168.100.222",
    netmask: "255.255.255.0"
end

config.vm.define "vm23" do |vm23|
  vm23.vm.host_name = "alpinevm23"
  vm23.vm.network "public_network",
    ip: "192.168.100.223",
    netmask: "255.255.255.0"
end

config.vm.define "vm24" do |vm24|
  vm24.vm.host_name = "alpinevm24"
  vm24.vm.network "public_network",
    ip: "192.168.100.224",
    netmask: "255.255.255.0"
end

config.vm.define "vm25" do |vm25|
  vm25.vm.host_name = "alpinevm25"
  vm25.vm.network "public_network",
    ip: "192.168.100.225",
    netmask: "255.255.255.0"
end

config.vm.define "vm26" do |vm26|
  vm26.vm.host_name = "alpinevm26"
  vm26.vm.network "public_network",
    ip: "192.168.100.226",
    netmask: "255.255.255.0"
end

config.vm.define "vm27" do |vm27|
  vm27.vm.host_name = "alpinevm27"
  vm27.vm.network "public_network",
    ip: "192.168.100.227",
    netmask: "255.255.255.0"
end

config.vm.define "vm28" do |vm28|
  vm28.vm.host_name = "alpinevm28"
  vm28.vm.network "public_network",
    ip: "192.168.100.228",
    netmask: "255.255.255.0"
end

config.vm.define "vm29" do |vm29|
  vm29.vm.host_name = "alpinevm29"
  vm29.vm.network "public_network",
    ip: "192.168.100.229",
    netmask: "255.255.255.0"
end

config.vm.define "vm30" do |vm30|
  vm30.vm.host_name = "alpinevm30"
  vm30.vm.network "public_network",
    ip: "192.168.100.230",
    netmask: "255.255.255.0"
end

end
