# -*- mode: ruby -*-
# vi: set ft=ruby :

@allhosts = {
  vm1: {
    hostname:     "CentOS7vm1",
    ip:           "192.168.56.121",
    netmask:      "255.255.255.0",
    network_type: "private_network",   #or public_network, or forwarded_port
    gui:          false,
    memory:       "768",
    cpus:         "1",
    command: [
      "yum install httpd -y",
      "systemctl start httpd",
    ],
  },

  vm2: {
    hostname:     "CentOS7vm2",
    ip:           "192.168.56.122",
    netmask:      "255.255.255.0",
    network_type: "private_network",   #or public_network, or forwarded_port
    gui:          false,
    memory:       "1024",
    cpus:         "1",
    command: [
      "yum install samba -y",
      "systemctl start smb nmb",
    ],
  },
}

load "./Vagrantfile.common.rb" if File.exist?("./Vagrantfile.common.rb")
